<?php get_header(); ?>
<main>
  <section class="hero">
    <img class="hero__bg" src="<?php seven_s_asset('victory-lane.jpg'); ?>" alt="Nick Shannon celebrating with the Seven S race car in victory lane">
    <div class="container hero__content"><p class="eyebrow">Council Bluffs, Iowa · Dirt Track Racing</p><h1 class="display">Seven S <span>Racing</span></h1><p class="hero__lead">Built on grit, family, and the local partners who make every lap possible. Follow Nick Shannon and the 7<sup>S</sup> from the shop to the checkered flag.</p><div class="hero__actions"><a class="button" href="#next-race">Next Race</a><a class="button button--ghost" href="<?php echo esc_url(home_url('/racing/')); ?>">From the Track</a></div></div>
  </section><div class="stripe"></div>

  <section class="split"><div class="split__image"><img src="<?php seven_s_asset('car-side.jpg'); ?>" alt="Side profile of the orange, blue, silver, and black Seven S race car"></div><div class="split__content"><div><p class="eyebrow">Meet the Driver</p><h2 class="display">Nick<br>Shannon</h2><p>Seven S Racing is a grassroots dirt-track team based in Council Bluffs, Iowa. Driver Nick Shannon brings the unmistakable 7<sup>S</sup> to race nights with the support of family, friends, and dedicated local businesses.</p><p>More of Nick’s racing story, car specifications, class, and season goals will be added after the team verifies them.</p><div class="stats"><div class="stat"><strong>7<sup>S</sup></strong><span>Car Number</span></div><div class="stat"><strong>IA</strong><span>Home State</span></div><div class="stat"><strong>Dirt</strong><span>Home Surface</span></div></div></div></div></section>

  <section id="next-race" class="race-board"><div class="container"><p class="eyebrow">At a Glance</p><h2 class="display section-title">Race Day</h2><div class="race-board__grid">
    <?php $events=seven_s_query('seven_s_event',1,'_seven_s_date','ASC'); if($events->have_posts()): while($events->have_posts()):$events->the_post(); ?><article class="race-card"><span class="eyebrow">Next Race</span><h3><?php the_title(); ?></h3><div class="race-card__meta"><span><strong><?php echo esc_html(get_post_meta(get_the_ID(),'_seven_s_date',true)); ?></strong><br>Date & time</span><span><strong><?php echo esc_html(get_post_meta(get_the_ID(),'_seven_s_location',true)); ?></strong><br>Location</span></div><span class="race-card__watermark">7</span></article><?php endwhile; wp_reset_postdata(); else: ?><article class="race-card"><span class="eyebrow">Next Race</span><h3>Schedule<br>Coming Soon</h3><div class="race-card__meta"><span>Nick’s next confirmed race will appear here.</span></div><span class="race-card__watermark">7</span></article><?php endif; ?>
    <?php $results=seven_s_query('seven_s_result',1,'_seven_s_result_date'); if($results->have_posts()): while($results->have_posts()):$results->the_post(); ?><article class="race-card race-card--result"><span class="eyebrow">Latest Result</span><h3><?php echo esc_html(get_post_meta(get_the_ID(),'_seven_s_finish',true)); ?></h3><div class="race-card__meta"><span><strong><?php the_title(); ?></strong><br><?php echo esc_html(get_post_meta(get_the_ID(),'_seven_s_class',true)); ?></span></div><span class="race-card__watermark">S</span></article><?php endwhile; wp_reset_postdata(); else: ?><article class="race-card race-card--result"><span class="eyebrow">Latest Result</span><h3>Race Recaps<br>Coming Soon</h3><div class="race-card__meta"><span>Verified finishes and reports will be posted here.</span></div><span class="race-card__watermark">S</span></article><?php endif; ?>
  </div></div></section>

  <section class="partners"><div class="container"><div class="partners__head"><div><p class="eyebrow">Sponsors Corner</p><h2 class="display section-title">Our Racing<br>Partners</h2></div><p>Seven S Racing is proud to represent the businesses and people who keep the 7<sup>S</sup> on track. Primary and local partners receive a direct link here—contingency decals are intentionally not treated as featured sponsors.</p></div><div class="partner-grid">
    <?php $sponsors=seven_s_query('seven_s_sponsor',12,'_seven_s_order','ASC'); if($sponsors->have_posts()): while($sponsors->have_posts()):$sponsors->the_post(); $url=get_post_meta(get_the_ID(),'_seven_s_url',true); ?><a class="partner" href="<?php echo esc_url($url ?: '#'); ?>" <?php echo $url ? 'target="_blank" rel="noopener"' : ''; ?>><?php if(has_post_thumbnail()): the_post_thumbnail('medium'); else: ?><strong><?php the_title(); ?></strong><small><?php echo esc_html(get_post_meta(get_the_ID(),'_seven_s_level',true)); ?></small><?php endif; ?></a><?php endwhile; wp_reset_postdata(); else: ?><div class="partner"><strong>Yogi’s Place</strong><small>Ainsworth, Nebraska</small></div><div class="partner"><strong>Charger Chassis</strong><small>Rising City, Nebraska</small></div><div class="partner"><strong>Kohlleppel</strong><small>Sawmill Services</small></div><div class="partner partner--pdc"><strong>Patriot Digital Collective</strong><small>Official supporting sponsor</small></div><?php endif; ?>
  </div></div></section>

  <section class="gallery-section"><div class="container"><p class="eyebrow">Latest from the Track</p><h2 class="display section-title">Race Night<br>Unfiltered</h2><div class="gallery-grid"><figure><img src="<?php seven_s_asset('victory-team.jpg'); ?>" alt="Nick Shannon and team in victory lane"><figcaption>Victory Lane</figcaption></figure><figure><img src="<?php seven_s_asset('car-angle-a.jpg'); ?>" alt="Seven S race car"><figcaption>The 7S</figcaption></figure><figure><img src="<?php seven_s_asset('victory-lane.jpg'); ?>" alt="Nick Shannon celebrating a win"><figcaption>Checkered Flag</figcaption></figure><figure><img src="<?php seven_s_asset('car-angle-b.jpg'); ?>" alt="Seven S race car side view"><figcaption>Built to Race</figcaption></figure></div><p style="margin-top:35px"><a class="button" href="<?php echo esc_url(home_url('/racing/')); ?>">See Racing & Gallery</a></p></div></section>

  <section class="merch-teaser"><img class="merch-teaser__bg" src="<?php seven_s_asset('merch.jpg'); ?>" alt="Seven S Racing shirt artwork"><div class="container merch-teaser__content"><p class="eyebrow">Official Seven S Gear</p><h2 class="display">Wear<br>The 7<sup>S</sup></h2><p>Shirts, hoodies, and track-ready gear are on the horizon. The first store release is being planned now.</p><a class="button" href="<?php echo esc_url(home_url('/merch/')); ?>">Merch Coming Soon</a></div></section>
</main><?php get_footer(); ?>
