<?php /* Template Name: Racing */ get_header(); ?>
<main>
<section class="page-hero"><div class="container"><p class="eyebrow">Seven S Racing</p><h1 class="display">From The Track</h1><p>Race reports, verified results, the upcoming schedule, and life around the 7<sup>S</sup>.</p></div></section>
<section class="schedule-section"><div class="container"><p class="eyebrow">Race Schedule</p><h2 class="display section-title">Full Schedule</h2><div class="schedule-list">
<?php $schedule=new WP_Query(['post_type'=>'seven_s_event','posts_per_page'=>-1,'post_status'=>'publish','meta_key'=>'_seven_s_date','orderby'=>'meta_value','order'=>'ASC']); if($schedule->have_posts()):while($schedule->have_posts()):$schedule->the_post();$race_date=get_post_meta(get_the_ID(),'_seven_s_date',true);$status=get_post_meta(get_the_ID(),'_seven_s_event_status',true)?:'scheduled'; ?>
<article class="schedule-row schedule-row--<?php echo esc_attr($status); ?>"><time datetime="<?php echo esc_attr($race_date); ?>"><strong><?php echo esc_html(wp_date('M j',strtotime($race_date))); ?></strong><span><?php echo esc_html(wp_date('Y',strtotime($race_date))); ?></span></time><div><span class="schedule-status"><?php echo esc_html($status); ?></span><h3><?php the_title(); ?></h3><p><?php echo esc_html(get_post_meta(get_the_ID(),'_seven_s_track',true)); ?> · <?php echo esc_html(get_post_meta(get_the_ID(),'_seven_s_location',true)); ?></p></div><?php $event_url=get_post_meta(get_the_ID(),'_seven_s_event_url',true);if($event_url):?><a class="button button--ghost" href="<?php echo esc_url($event_url); ?>" target="_blank" rel="noopener">Event Details</a><?php endif;?></article>
<?php endwhile;wp_reset_postdata();else:?><article class="race-card"><span class="eyebrow">Schedule update</span><h3>More dates coming soon</h3><p>Nick’s confirmed race dates will appear here.</p></article><?php endif;?></div></div></section>
<section class="content-section"><div class="container"><p class="eyebrow">Race Reports</p><h2 class="display section-title">Latest Stories</h2><div class="post-grid"><?php $posts=new WP_Query(['post_type'=>'post','posts_per_page'=>6]); if($posts->have_posts()):while($posts->have_posts()):$posts->the_post(); ?><a class="post-card" href="<?php the_permalink(); ?>"><div class="post-card__media"><?php if(has_post_thumbnail()) the_post_thumbnail('seven-s-card'); ?></div><div class="post-card__body"><span class="eyebrow"><?php echo esc_html(get_the_date()); ?></span><h3><?php the_title(); ?></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),18)); ?></p></div></a><?php endwhile;wp_reset_postdata();else:?><article class="race-card"><span class="eyebrow">First report</span><h3>Coming after the next green flag</h3><p>Nick’s published race recaps will automatically appear here.</p></article><?php endif;?></div></div></section>
<section class="gallery-section"><div class="container"><p class="eyebrow">7S Gallery</p><h2 class="display section-title">Behind The Wheel</h2><div class="gallery-grid"><?php $gallery=seven_s_query('seven_s_gallery',4);if($gallery->have_posts()):while($gallery->have_posts()):$gallery->the_post();if(has_post_thumbnail()):?><figure><?php the_post_thumbnail('large');?><figcaption><?php the_title();?></figcaption></figure><?php endif;endwhile;wp_reset_postdata();else:?><figure><img src="<?php seven_s_asset('victory-team.jpg');?>" alt="Victory lane"><figcaption>Victory Lane</figcaption></figure><figure><img src="<?php seven_s_asset('car-side.jpg');?>" alt="Seven S race car"><figcaption>The Car</figcaption></figure><figure><img src="<?php seven_s_asset('victory-lane.jpg');?>" alt="Race win"><figcaption>Race Night</figcaption></figure><figure><img src="<?php seven_s_asset('car-angle-b.jpg');?>" alt="Seven S car"><figcaption>Behind the Scenes</figcaption></figure><?php endif;?></div></div></section>
</main><?php get_footer(); ?>
